---
title: "Hierarchical models Exercises"
format: pdf
editor: visual
---

## Exercise 1 Modeling the Impact of Climate Change

Using the **ITEX diversity dataset** , think about a research question you could ask regarding the impact of **one aspect of climate change** on **a variable of interest**, across different sites.

Explore your research question using modeling tools you learned in today's lecture.

👉 Your Tasks:

1.  **Model Planning**:
    -   What is your **response variable**?
    -   Which variables make sense as **fixed effects**?
    -   Which variable(s) should be treated as **random effects** (e.g., site, year)?
2.  **Fit the Model**:
    -   Use `lmer()` to fit a model to the data and look at the output with `summary()`.
3.  **Reflect**:
    -   Does the model structure reflect **how the data was collected**?

## Exercise 2 (optional)

What is the impact of climate change on your variable of interest **within sites**?

Now that you've explored overall patterns, focus your model on how **climate change impacts your variable of interest, within each site**.

👉 Your Tasks:

1.  

    -   What changes when we ask about relationships *within sites* instead of *across* them?
    -   Should you adjust the way `site` is treated in your model?

2.  **Model Check**:

3.  **Fit a New Model (if needed)**:

    -   Update your `lmer()` call to reflect this new focus.
    -   Reinterpret the output
